author: Eindhovense Studenten Taekwondo Vereniging Ilyeo

outputdir: result
inputdir: input

alsocopy:
  - ".*\\.jpg"
  - ".*\\.png"
  - ".*\\.js"
  - ".*\\.css"
  - ".*\\.pdf"

menu:
  -
    menu: Home
    title: Home
    contents: index.html
    keywords: "Ilyeo, taekwondo, tae kwon do"
    description: "Geef je nieuwe semester een KICK start en kom met ons meetrainen! Een afwisselende en gezellige manier om (weer) fit te worden. "
  -
    menu: Taekwondo
    title: Taekwondo
    contents: taekwondo.html
    keywords: "Taekwondo,tae kwon do"
    description: "Taekwondo is voor iedereen, je traint op je eigen tempo en mogelijkheden. Wil je voorzichtig trainen, geen probleem. "
  -
    menu: Vereniging
    title: De vereniging
    contents: vereniging.html
    keywords: "ilyeo,vereniging,eindhoven,studenten,sportcentrum"
    description: Over Ilyeo
  -
    menu: Trainers
    title: Trainers
    contents: trainers.html
    keywords: "ilyeo,trainers,eindhoven,studenten,sportcentrum"
    description: De trainers van E.S.T.V. Ilyeo
    noshow: true
  -
    menu: Vorige besturen
    title: Vorige besturen van Ilyeo
    contents: besturen.html
    keywords: "ilyeo,besturen,eindhoven,studenten,sportcentrum"
    description: De oud-besturen van E.S.T.V. Ilyeo
    noshow: true
  -
    menu: Trainingen
    title: Trainingen
    contents: trainingen.html
    keywords: "trainingen,ilyeo,sportcentrum,rooster"
    description: We trainen op maandag- en donderdagavond
  -
    menu: Examens
    title: Examens
    contents: examens.html
    keywords: "banden,examens,bandenexamens,ilyeo,taekwondo"
    description: Bandenexamens
  -
    menu: Exameneisen
    title: Exameneisen
    contents: exameneisen.html
    keywords: "banden,examens,bandenexamens,ilyeo,taekwondo"
    description: Exameneisen per band